name: Code Review Trigger

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'code review' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Pull Request URL
      uses: kceb/pull-request-url-action@v2
      id: pr-url
    
    - name: CR notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_CR_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Tem [Pull Request](${{ steps.pr-url.outputs.url }}) novo aguardando pra receber CR! :technologist:'
