name: CI

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'code review' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Failure notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_CR_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '(ODYSSEUS) Novo PR pronto pra receber CR! :technologist:'
