name: Deploy

on:
  push:
    branches:
      - master

jobs:
  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Run linter
        run: yarn lint
      
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn

  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.3]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Run tests
        run: yarn test
      
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
