# Esse workflow executa os testes

name: "Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn
    
    - name: Install Dependencies
      run: yarn install
    
    - name: Run tests
      run: yarn test
    
    - name: Uninstall Yarn
      if: always()
      run: npm uninstall -g yarn
